format_version: 7
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

workflows:
  ci:
    steps:
    - go-list:
    - golint:
    - errcheck:
    - go-test:

  dep-update:
    title: Dep update
    description: |
      Used for updating bitrise dependencies with dep
    steps:
    - script:
        title: Dependency update
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            go get -u -v github.com/golang/dep/cmd/dep
            dep ensure -v
            dep ensure -v -update