[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-tools/go-steputils"

[[constraint]]
  name = "github.com/qri-io/jsonschema"
  version = "0.1.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.5.1"

[prune]
  go-tests = true
  unused-packages = true
